---
- name: Install Clickhouse
  tags: clickhouse
  hosts: clickhouse
  roles:
    - clickhouse

- name: Install vector
  tags: vector
  hosts: vector
  roles:
    - vector

- name: Install lighthouse
  hosts: lighthouse
  tags: nginx
  roles:
    - lighthouse
